from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .io import load_redirect_csv, load_url_records, write_json, write_redirect_csv
from .matcher import generate_redirect_map, render_server_rules
from .report import mapping_issues, mapping_summary, render_mapping_html, render_validation_html
from .validate import validate_redirects


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="rankguard",
        description="Local-first SEO migration guardrails for redirect maps and launch validation.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    plan = subparsers.add_parser("plan", help="Generate a redirect map and migration-risk report.")
    plan.add_argument("--old", required=True, help="Old sitemap, crawler CSV, or one-URL-per-line file.")
    plan.add_argument("--new", required=True, help="New sitemap, staging crawl CSV, or one-URL-per-line file.")
    plan.add_argument("--redirects", help="Write candidate redirects to CSV.")
    plan.add_argument("--report", help="Write an HTML migration report.")
    plan.add_argument("--json", help="Write a JSON migration report.")
    plan.add_argument("--rules", help="Write server redirect rules.")
    plan.add_argument("--rules-format", choices=["nginx", "apache"], default="nginx")
    plan.add_argument("--min-score", type=_score, default=0.58, help="Minimum match score from 0 to 1.")
    plan.add_argument(
        "--fail-on-issues",
        action="store_true",
        help="Exit non-zero when old URLs remain unmatched. Useful for CI gates.",
    )
    plan.set_defaults(func=_plan)

    validate = subparsers.add_parser("validate", help="Validate planned redirects against live URLs.")
    validate.add_argument("--redirects", required=True, help="Redirect CSV generated by rankguard plan.")
    validate.add_argument("--report", help="Write an HTML launch validation report.")
    validate.add_argument("--json", help="Write JSON launch validation results.")
    validate.add_argument("--timeout", type=_positive_int, default=15)
    validate.add_argument("--max-hops", type=_non_negative_int, default=8)
    validate.add_argument("--limit", type=_positive_int, help="Validate only the first N redirects.")
    validate.set_defaults(func=_validate)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (OSError, ValueError) as exc:
        print(f"rankguard: error: {exc}", file=sys.stderr)
        return 1


def _plan(args: argparse.Namespace) -> int:
    if args.old == "-" and args.new == "-":
        raise ValueError("Only one plan input can read from stdin.")

    old_records = load_url_records(args.old)
    new_records = load_url_records(args.new)
    if not old_records:
        raise ValueError(f"No old URLs found in {args.old}.")
    if not new_records:
        raise ValueError(f"No new URLs found in {args.new}.")

    result = generate_redirect_map(old_records, new_records, min_score=args.min_score)
    summary = mapping_summary(result)
    written: list[tuple[str, str]] = []

    if args.redirects:
        write_redirect_csv(result.candidates, args.redirects)
        written.append(("redirect CSV", args.redirects))
    if args.report:
        _write_text(args.report, render_mapping_html(result, old_source=args.old, new_source=args.new))
        written.append(("HTML report", args.report))
    if args.json:
        write_json(
            {
                "summary": summary,
                "issues": [issue.__dict__ for issue in mapping_issues(result)],
                "result": result.to_dict(),
            },
            args.json,
        )
        written.append(("JSON report", args.json))
    if args.rules:
        _write_text(args.rules, render_server_rules(result.candidates, fmt=args.rules_format))
        written.append((f"{args.rules_format} rules", args.rules))

    _print_plan_summary(summary, old_count=len(old_records), new_count=len(new_records), written=written)
    if args.fail_on_issues and summary["unmatched_old"]:
        return 2
    return 0


def _validate(args: argparse.Namespace) -> int:
    candidates = load_redirect_csv(args.redirects)
    if not candidates:
        raise ValueError(f"No redirects found in {args.redirects}.")
    results = validate_redirects(
        candidates,
        timeout=args.timeout,
        max_hops=args.max_hops,
        limit=args.limit,
    )
    written: list[tuple[str, str]] = []
    if args.report:
        _write_text(args.report, render_validation_html(results))
        written.append(("HTML report", args.report))
    if args.json:
        write_json([result.to_dict() for result in results], args.json)
        written.append(("JSON results", args.json))

    failures = [result for result in results if not result.ok]
    _print_validation_summary(total=len(results), failures=len(failures), written=written)
    return 0 if not failures else 2


def _write_text(path: str, text: str) -> None:
    target = Path(path).expanduser()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")


def _print_plan_summary(
    summary: dict[str, int | float],
    *,
    old_count: int,
    new_count: int,
    written: list[tuple[str, str]],
) -> None:
    print("RankGuard plan summary")
    print(f"  Inputs: {old_count} old URLs, {new_count} new URLs")
    print(
        "  Mappings: {mapped} mapped, {unmatched_old} unmatched old, "
        "{low_confidence} low confidence, {conflicts} many-to-one targets".format(**summary)
    )
    print(
        "  Confidence: {high_confidence} high, {medium_confidence} medium, "
        "{low_confidence} low; min score {min_score:.2f}".format(**summary)
    )
    _print_written(written, empty_hint="No files written. Add --redirects, --report, --json, or --rules.")
    if summary["unmatched_old"]:
        print("  Review: unmatched old URLs need manual targets before launch.")


def _print_validation_summary(*, total: int, failures: int, written: list[tuple[str, str]]) -> None:
    print("RankGuard validation summary")
    print(f"  Redirects checked: {total}")
    print(f"  Result: {total - failures} passed, {failures} failed")
    _print_written(written, empty_hint="No files written. Add --report or --json.")


def _print_written(written: list[tuple[str, str]], *, empty_hint: str) -> None:
    if not written:
        print(f"  Output: {empty_hint}")
        return
    print("  Output:")
    for label, path in written:
        print(f"    {label}: {path}")


def _score(value: str) -> float:
    try:
        score = float(value)
    except ValueError:
        raise argparse.ArgumentTypeError("must be a number from 0 to 1") from None
    if not 0 <= score <= 1:
        raise argparse.ArgumentTypeError("must be from 0 to 1")
    return score


def _positive_int(value: str) -> int:
    try:
        number = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError("must be a positive integer") from None
    if number < 1:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return number


def _non_negative_int(value: str) -> int:
    try:
        number = int(value)
    except ValueError:
        raise argparse.ArgumentTypeError("must be zero or a positive integer") from None
    if number < 0:
        raise argparse.ArgumentTypeError("must be zero or a positive integer")
    return number
