from __future__ import annotations

import re
from collections import Counter, defaultdict
from difflib import SequenceMatcher
from urllib.parse import urlparse

from .models import MappingResult, RedirectCandidate, URLRecord
from .normalize import (
    normalize_url,
    normalized_path,
    section_key,
    segment_tokens,
    tail_slug,
    title_tokens,
    url_tokens,
)


def generate_redirect_map(
    old_records: list[URLRecord],
    new_records: list[URLRecord],
    *,
    min_score: float = 0.58,
    alternatives: int = 3,
) -> MappingResult:
    """Generate the best redirect candidate for each old URL."""
    new_by_url = {record.url: record for record in new_records}
    pool_index = _build_pool_index(new_records)

    candidates: list[RedirectCandidate] = []
    unmatched: list[URLRecord] = []

    for old in old_records:
        scored = []
        for pool_order, new in enumerate(_candidate_pool(old, new_records, pool_index)):
            score, reason = score_pair(old, new)
            scored.append((score, pool_order, reason, new))
        scored.sort(key=lambda item: (-item[0], item[1]))

        if not scored or scored[0][0] < min_score:
            unmatched.append(old)
            continue

        best_score, _pool_order, reason, best_new = scored[0]
        alt_limit = max(0, alternatives)
        alt = [(new.url, round(score, 3)) for score, _pool_order, _reason, new in scored[1 : alt_limit + 1]]
        candidates.append(
            RedirectCandidate(
                old_url=old.url,
                new_url=best_new.url,
                score=round(best_score, 3),
                confidence=_confidence(best_score),
                reason=reason,
                alternatives=alt,
            )
        )

    mapped_new = {candidate.new_url for candidate in candidates}
    orphan_new = [record for url, record in new_by_url.items() if url not in mapped_new]
    conflicts = _find_conflicts(candidates)

    return MappingResult(
        candidates=candidates,
        unmatched_old=unmatched,
        orphan_new=orphan_new,
        conflicts=conflicts,
        min_score=min_score,
    )


def score_pair(old: URLRecord, new: URLRecord) -> tuple[float, str]:
    old_path = normalized_path(old.url)
    new_path = normalized_path(new.url)
    if old_path == new_path:
        return 1.0, "same normalized path"

    old_tokens = url_tokens(old.url)
    new_tokens = url_tokens(new.url)
    shared_tokens = old_tokens & new_tokens
    token_score = _jaccard(old_tokens, new_tokens)

    sequence_score = SequenceMatcher(None, old_path, new_path).ratio()
    old_tail = tail_slug(old.url)
    new_tail = tail_slug(new.url)
    old_tail_tokens = segment_tokens(old_tail)
    new_tail_tokens = segment_tokens(new_tail)
    tail_token_score = _jaccard(old_tail_tokens, new_tail_tokens)
    tail_score = 1.0 if old_tail and old_tail == new_tail else 0.0
    section_score = 1.0 if section_key(old.url) and section_key(old.url) == section_key(new.url) else 0.0
    title_score = _title_score(old.title, new.title)
    numeric_bonus = 0.08 if _shared_numeric_token(shared_tokens) else 0.0

    score = (
        sequence_score * 0.25
        + token_score * 0.22
        + tail_token_score * 0.18
        + tail_score * 0.22
        + section_score * 0.07
        + title_score * 0.06
        + numeric_bonus
    )
    if tail_score and len(old_tail_tokens) >= 2 and token_score >= 0.45:
        score = max(score, 0.88)
    elif tail_score and token_score >= 0.50:
        score = max(score, 0.78)
    elif old_tail and new_tail and tail_token_score == 1.0 and token_score >= 0.50:
        score = max(score, 0.74)
    score = min(score, 0.99)

    reasons = []
    if tail_score:
        reasons.append("same slug")
    elif tail_token_score:
        reasons.append("similar slug")
    if section_score:
        reasons.append("same section")
    if shared_tokens:
        reasons.append(f"shared tokens: {', '.join(sorted(shared_tokens)[:5])}")
    if title_score:
        reasons.append("similar title")
    if not reasons:
        reasons.append("path similarity")
    return score, "; ".join(reasons)


def render_server_rules(candidates: list[RedirectCandidate], *, fmt: str) -> str:
    lines = []
    if fmt == "nginx":
        lines.append("# Generated by RankGuard. Review before deploying.")
        for candidate in candidates:
            target = normalize_url(candidate.new_url, keep_query=True)
            lines.append(f"location = {_path(candidate.old_url)} {{ return 301 {target}; }}")
        return "\n".join(lines) + "\n"

    if fmt == "apache":
        lines.append("# Generated by RankGuard. Review before deploying.")
        lines.append("RewriteEngine On")
        for candidate in candidates:
            pattern = re.escape(_path(candidate.old_url).lstrip("/"))
            target = normalize_url(candidate.new_url, keep_query=True)
            lines.append(f"RewriteRule ^{pattern}$ {target} [R=301,L]")
        return "\n".join(lines) + "\n"

    raise ValueError("rules format must be 'nginx' or 'apache'")


def _build_pool_index(new_records: list[URLRecord]) -> dict[str, dict[str, list[int]]]:
    by_path: dict[str, list[int]] = defaultdict(list)
    by_tail: dict[str, list[int]] = defaultdict(list)
    by_token: dict[str, list[int]] = defaultdict(list)
    by_section: dict[str, list[int]] = defaultdict(list)
    for index, record in enumerate(new_records):
        by_path[normalized_path(record.url)].append(index)
        if tail_slug(record.url):
            by_tail[tail_slug(record.url)].append(index)
        if section_key(record.url):
            by_section[section_key(record.url)].append(index)
        for token in url_tokens(record.url):
            by_token[token].append(index)
    return {"path": by_path, "tail": by_tail, "token": by_token, "section": by_section}


def _candidate_pool(
    old: URLRecord,
    new_records: list[URLRecord],
    pool_index: dict[str, dict[str, list[int]]],
    *,
    max_candidates: int = 400,
) -> list[URLRecord]:
    counter: Counter[int] = Counter()
    counter.update({index: 8 for index in pool_index["path"].get(normalized_path(old.url), [])})

    tail = tail_slug(old.url)
    if tail:
        counter.update({index: 5 for index in pool_index["tail"].get(tail, [])})
    section = section_key(old.url)
    if section:
        counter.update({index: 2 for index in pool_index["section"].get(section, [])})
    for token in sorted(url_tokens(old.url)):
        counter.update(pool_index["token"].get(token, []))

    if not counter:
        return new_records[:max_candidates] if len(new_records) > max_candidates else new_records
    ranked = sorted(counter.items(), key=lambda item: (-item[1], item[0]))
    return [new_records[index] for index, _count in ranked[:max_candidates]]


def _title_score(old_title: str, new_title: str) -> float:
    if not old_title or not new_title:
        return 0.0
    old = title_tokens(old_title)
    new = title_tokens(new_title)
    return _jaccard(old, new)


def _shared_numeric_token(tokens: set[str]) -> bool:
    return any(any(char.isdigit() for char in token) for token in tokens)


def _confidence(score: float) -> str:
    if score >= 0.86:
        return "high"
    if score >= 0.70:
        return "medium"
    return "low"


def _find_conflicts(candidates: list[RedirectCandidate]) -> dict[str, list[str]]:
    targets: dict[str, list[str]] = defaultdict(list)
    for candidate in candidates:
        targets[candidate.new_url].append(candidate.old_url)
    return {target: sources for target, sources in targets.items() if len(sources) > 3}


def _path(url: str) -> str:
    parsed = urlparse(normalize_url(url))
    return parsed.path or "/"


def _jaccard(left: set[str], right: set[str]) -> float:
    union = left | right
    return len(left & right) / len(union) if union else 0.0
